pipeline:
  test:
    image: node:10.16.0-slim
    commands:
      - node -v
      - npm -v
      - yarn -v
      - yarn install
      - yarn lint
      - yarn tsc

  build:
    image: node:10.16.0-slim
    commands:
      - yarn build

  docker_publish:
    image: plugins/docker
    repo: erxes/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_BRANCH}-latest
    when:
      branch:
        - master
        - develop
      event: push
      status: success

  docker_publish_tag:
    image: plugins/docker
    repo: erxes/${DRONE_REPO_NAME}
    dockerfile: Dockerfile
    secrets:
      - source: docker_hub_username
        target: docker_username
      - source: docker_hub_password
        target: docker_password
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
      status: success